version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fx_deals_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fx_deals
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/schema.sql
    ports:
      - "8080:8080"
    networks:
      - fx-network

  postgres:
    image: postgres:15
    container_name: fx-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fx-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fx-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - fx-network

networks:
  fx-network:
    driver: bridge